-- GENERATED by tools/gen-luacheck.js. Do not edit by hand.
-- Regenerate with `npm run gen-luacheck`; CI runs it with --check.
--
-- Applies to the test tree only.
--
-- The suite runs with no FiveM server, so it builds one: it assigns the
-- natives, the runtime functions and the exports table as ordinary Lua
-- globals and then loads the real shipped source on top of them. Under the
-- root config those names are read-only, which is correct for shipped code
-- and wrong for a harness.
--
-- This is a statement about the directory, not a suppression. The same
-- assignment in client/ or server/ is still a W121, and the 179 findings
-- this removes were all of them being tests doing their job.

std = "lua54"
max_line_length = false
codes = true
unused = true
unused_secondaries = true
self = false
-- Same reasoning for parameters. A stub for a native has to match the
-- arity of that native, or the code under test passes the wrong number of
-- arguments and the failure surfaces somewhere else entirely:
--   function(hash, x, y, z) return entity end   -- CreateObject
-- Six parameters, five unused, and every one of them has to be there.
-- In shipped code an unused parameter is a real smell and stays reported.
unused_args = false

-- 324 names writable in this directory.
globals = {
    "AddCommand", "AddEventHandler", "AddTextComponentString",
    "AddTextComponentSubstringPlayerName", "BeginTextCommandDisplayText",
    "BeginTextCommandThefeedPost", "CIS_API_REAL", "CIS_DUMP_TARGET", "CIS_LIVE_ENV",
    "CIS_SUITE_MODE", "CIS_TEST_FILES", "Cis", "CisCache", "CisConfigUtil", "CisCurve",
    "CisDefaults", "CisDetect", "CisForgetPlayer", "CisGrid", "CisHeap", "CisHistogram",
    "CisId", "CisInterp", "CisInvokingAllowed", "CisJobCount", "CisJson", "CisLRU",
    "CisLibFailed", "CisLibReady", "CisLog", "CisNetOn", "CisOwned", "CisPending",
    "CisRandom", "CisRate", "CisRateBucketCount", "CisRateOk", "CisReadyState",
    "CisRegisterCallback", "CisRegistry", "CisRememberJob", "CisSecurityRebuild",
    "CisSecurityReport", "CisSemver", "CisSparse", "CisString", "CisSyncEnabled",
    "CisTable", "CisTime", "CisValidate", "CisWindow", "CisZonesContains", "CisZonesCreate",
    "CisZonesRemove", "Citizen", "ClearTimeout", "ClearVehicleCustomPrimaryColour",
    "ClearVehicleCustomSecondaryColour", "Config", "CreateObject", "CreatePed",
    "CreateThread", "CreateVehicle", "DebugLog", "DeleteEntity", "DiscordConfig",
    "DoesEntityExist", "DoesExtraExist", "DrawRect", "DrawText3D", "DropPlayer",
    "DropPlayerExtended", "EndResource", "EndTextCommandDisplayText",
    "EndTextCommandThefeedPostTicker", "ExecuteCommand", "FreezeEntityPosition",
    "GetAmmoInPedWeapon", "GetClosestVehicle", "GetCloudTimeAsInt", "GetConvar",
    "GetConvarBool", "GetConvarInt", "GetCurrentResourceName", "GetCurrentWeaponData",
    "GetDistanceBetweenCoords", "GetDriftTyresEnabled", "GetEntityCoords",
    "GetEntityHeading", "GetEntityModel", "GetEntityType", "GetFrameCount",
    "GetGameBuildNumber", "GetGameTimer", "GetGameplayCamFov", "GetInvokingResource",
    "GetIsVehiclePrimaryColourCustom", "GetIsVehicleSecondaryColourCustom",
    "GetNumPlayerIdentifiers", "GetNumPlayerIndices", "GetNumResourceMetadata",
    "GetNumResources", "GetOffsetFromEntityInWorldCoords", "GetPedAmmoTypeFromWeapon",
    "GetPedConfigFlag", "GetPedInVehicleSeat", "GetPlayerEndpoint", "GetPlayerFromIndex",
    "GetPlayerGUID", "GetPlayerIdentifier", "GetPlayerName", "GetPlayerPed",
    "GetPlayerPing", "GetPlayerRoutingBucket", "GetPlayerServerId", "GetPlayerToken",
    "GetPlayerVehicleSeat", "GetPlayers", "GetPlayersIdentifiers", "GetRealTime",
    "GetResourceByFindIndex", "GetResourceMetadata", "GetResourcePath", "GetResourceState",
    "GetSelectedPedWeapon", "GetShapeTestResult", "GetTableSize", "GetVehicleBodyHealth",
    "GetVehicleColours", "GetVehicleCustomPrimaryColour", "GetVehicleCustomSecondaryColour",
    "GetVehicleDashboardColour", "GetVehicleDirtLevel", "GetVehicleEngineHealth",
    "GetVehicleExtraColours", "GetVehicleFuelLevel", "GetVehicleInteriorColor",
    "GetVehicleLivery", "GetVehicleLiveryCount", "GetVehicleMaxNumberOfPassengers",
    "GetVehicleMod", "GetVehicleModColor_1", "GetVehicleModColor_2",
    "GetVehicleModVariation", "GetVehicleNeonLightsColour", "GetVehicleNumberPlateText",
    "GetVehicleNumberPlateTextIndex", "GetVehicleOilLevel", "GetVehiclePedIsIn",
    "GetVehiclePetrolTankHealth", "GetVehicleProperties", "GetVehicleRoofLivery",
    "GetVehicleTyreSmokeColor", "GetVehicleTyresCanBurst", "GetVehicleWheelSize",
    "GetVehicleWheelType", "GetVehicleWheelWidth", "GetVehicleWindowTint",
    "GetVehicleXenonLightsColor", "GetWeaponAttachments", "Globals", "HasModelLoaded",
    "HasPedGotWeaponComponent", "InvalidateIdleCam", "InvalidateVehicleIdleCam",
    "IsDuplicityVersion", "IsEntityAMissionEntity", "IsEntityDead", "IsModelInCdimage",
    "IsModelValid", "IsPedArmed", "IsPedInAnyVehicle", "IsPedShooting",
    "IsPlayerFreeAiming", "IsToggleModOn", "IsVehicleDoorDamaged", "IsVehicleExtraTurnedOn",
    "IsVehicleNeonLightEnabled", "IsVehicleTyreBurst", "IsVehicleWindowIntact", "Load",
    "LoadResourceFile", "LoadResourceFileAsync", "Logging", "NetworkDoesNetworkIdExist",
    "NetworkGetEntityFromNetworkId", "NetworkGetEntityIsNetworked", "NetworkGetEntityOwner",
    "NetworkGetNetworkIdFromEntity", "PerformHttpRequest", "PerformHttpRequestAsync",
    "Player", "PlayerId", "PlayerPedId", "RandomFloat", "RegisterCommand",
    "RegisterNUICallback", "RegisterNetEvent", "RemoveCommand", "RemoveEventHandler",
    "RemoveVehicleWindow", "RequestModel", "RequestModelTimeout", "RestartResource",
    "Round", "SUITE_NAMES", "SaveResourceFile", "Security", "SendNuiMessage",
    "SetBlockingOfNonTemporaryEvents", "SetDriftTyresEnabled", "SetEntityCoords",
    "SetEntityHeading", "SetEntityInvincible", "SetHttpHandler", "SetHttpTimeout",
    "SetInterval", "SetModelAsNoLongerNeeded", "SetNuiFocus", "SetPlayerRoutingBucket",
    "SetResourceKvp", "SetResourceKvpMulti", "SetTextCentre", "SetTextColour",
    "SetTextEntry", "SetTextFont", "SetTextProportional", "SetTextScale", "SetTimeout",
    "SetVehicleBodyHealth", "SetVehicleColours", "SetVehicleCustomPrimaryColour",
    "SetVehicleCustomSecondaryColour", "SetVehicleDirtLevel", "SetVehicleDoorBroken",
    "SetVehicleEngineHealth", "SetVehicleExtra", "SetVehicleExtraColours",
    "SetVehicleFixed", "SetVehicleFuelLevel", "SetVehicleLivery", "SetVehicleMod",
    "SetVehicleModColor_1", "SetVehicleModColor_2", "SetVehicleModKit",
    "SetVehicleNeonLightEnabled", "SetVehicleNeonLightsColour", "SetVehicleNumberPlateText",
    "SetVehicleNumberPlateTextIndex", "SetVehicleOilLevel", "SetVehiclePetrolTankHealth",
    "SetVehicleProperties", "SetVehicleRoofLivery", "SetVehicleTyreBurst",
    "SetVehicleTyreSmokeColor", "SetVehicleTyresCanBurst", "SetVehicleWheelType",
    "SetVehicleWindowTint", "StartExpensiveSynchronousShapeTestLosProbe", "StartResource",
    "StartScreenEffect", "StopResource", "StopScreenEffect", "TEST_CASES",
    "TaskStartScenarioInPlace", "ToggleVehicleMod", "TriggerClientEvent", "TriggerEvent",
    "TriggerLatentClientEvent", "TriggerNuiCallback", "TriggerServerEvent", "Wait",
    "WaitForLibReady", "World3dToScreen2d", "assert", "citizen", "collectgarbage",
    "coroutine", "debug", "dofile", "error", "exports", "getmetatable", "io", "ipairs",
    "joaat", "json", "load", "loads", "loadstring", "math", "matrix3", "next",
    "onClientResourceStart", "onClientResourceStop", "onResourceStart", "onResourceStop",
    "os", "pairs", "pcall", "print", "promise", "promise_new", "quaternion", "rawequal",
    "rawget", "rawset", "require", "select", "setmetatable", "source", "string", "table",
    "tonumber", "tostring", "type", "unpack", "vec2", "vec3", "vec4", "vector2", "vector3",
    "vector4", "xpcall",
}
