-- Real lint. `npm run lint`.
--
-- luacheck is not an npm dependency and is not installed by `npm ci`: CI
-- installs the pinned 1.2.0 release, so the library keeps its zero-runtime-
-- dependency property.
--
-- WHY TWO BLOCKS ARE GENERATED. The natives and runtime functions the shipped
-- code reads, and the globals the shipped code defines, are both facts about
-- the source rather than opinions, and both used to be hand-maintained. They
-- were hand-maintained badly enough that the globals block carried the single
-- entry "Cis.*" -- which luacheck cannot interpret as a pattern, so it matched
-- nothing and 1971 reads of the library's own globals were reported as
-- undefined. Both blocks are now generated by tools/gen-luacheck.js from the
-- native databases and from the source, and CI fails if they drift.

std = "lua54"

-- BEGIN GENERATED read_globals
-- GENERATED by tools/gen-luacheck.js. Do not edit by hand.
-- Regenerate with `npm run gen-luacheck`; CI runs it with --check.
--
-- Everything the FiveM runtime provides and the shipped code reads: the
-- natives this repository calls, and the CfxLua scheduler, event,
-- resource and type-construction functions. Realms are not encoded here --
-- `npm run check-realms` is what enforces those. This list only stops
-- luacheck reporting every FiveM call as an undefined global.
--
-- Names this repository defines itself are deliberately absent: a name in
-- both lists would be read-only here and writable below, and luacheck
-- resolves that to read-only.
--
-- 221 names, from 144 natives in use.
read_globals = {
    "AddCommand", "AddEventHandler", "AddTextComponentString",
    "AddTextComponentSubstringPlayerName", "BeginTextCommandDisplayText",
    "BeginTextCommandThefeedPost", "Citizen", "ClearTimeout",
    "ClearVehicleCustomPrimaryColour", "ClearVehicleCustomSecondaryColour", "CreateObject",
    "CreateThread", "CreateVehicle", "DeleteEntity", "DoesEntityExist", "DoesExtraExist",
    "DrawRect", "DropPlayer", "DropPlayerExtended", "EndResource",
    "EndTextCommandDisplayText", "EndTextCommandThefeedPostTicker", "ExecuteCommand",
    "FreezeEntityPosition", "GetAmmoInPedWeapon", "GetCloudTimeAsInt", "GetConvar",
    "GetConvarBool", "GetConvarInt", "GetCurrentResourceName", "GetDriftTyresEnabled",
    "GetEntityCoords", "GetEntityHeading", "GetEntityModel", "GetEntityType",
    "GetFrameCount", "GetGameBuildNumber", "GetGameTimer", "GetGameplayCamFov",
    "GetInvokingResource", "GetIsVehiclePrimaryColourCustom",
    "GetIsVehicleSecondaryColourCustom", "GetNumPlayerIdentifiers", "GetNumPlayerIndices",
    "GetNumResourceMetadata", "GetNumResources", "GetOffsetFromEntityInWorldCoords",
    "GetPedAmmoTypeFromWeapon", "GetPedConfigFlag", "GetPedInVehicleSeat",
    "GetPlayerEndpoint", "GetPlayerFromIndex", "GetPlayerGUID", "GetPlayerIdentifier",
    "GetPlayerName", "GetPlayerPed", "GetPlayerPing", "GetPlayerRoutingBucket",
    "GetPlayerServerId", "GetPlayerToken", "GetPlayers", "GetPlayersIdentifiers",
    "GetRealTime", "GetResourceByFindIndex", "GetResourceMetadata", "GetResourcePath",
    "GetResourceState", "GetSelectedPedWeapon", "GetShapeTestResult",
    "GetVehicleBodyHealth", "GetVehicleColours", "GetVehicleCustomPrimaryColour",
    "GetVehicleCustomSecondaryColour", "GetVehicleDashboardColour", "GetVehicleDirtLevel",
    "GetVehicleEngineHealth", "GetVehicleExtraColours", "GetVehicleFuelLevel",
    "GetVehicleInteriorColor", "GetVehicleLivery", "GetVehicleLiveryCount",
    "GetVehicleMaxNumberOfPassengers", "GetVehicleMod", "GetVehicleModColor_1",
    "GetVehicleModColor_2", "GetVehicleModVariation", "GetVehicleNeonLightsColour",
    "GetVehicleNumberPlateText", "GetVehicleNumberPlateTextIndex", "GetVehicleOilLevel",
    "GetVehiclePedIsIn", "GetVehiclePetrolTankHealth", "GetVehicleRoofLivery",
    "GetVehicleTyreSmokeColor", "GetVehicleTyresCanBurst", "GetVehicleWheelSize",
    "GetVehicleWheelType", "GetVehicleWheelWidth", "GetVehicleWindowTint",
    "GetVehicleXenonLightsColor", "HasModelLoaded", "HasPedGotWeaponComponent",
    "InvalidateIdleCam", "InvalidateVehicleIdleCam", "IsDuplicityVersion",
    "IsModelInCdimage", "IsModelValid", "IsPedArmed", "IsPedInAnyVehicle", "IsPedShooting",
    "IsPlayerFreeAiming", "IsToggleModOn", "IsVehicleDoorDamaged", "IsVehicleExtraTurnedOn",
    "IsVehicleNeonLightEnabled", "IsVehicleTyreBurst", "IsVehicleWindowIntact", "Load",
    "LoadResourceFile", "LoadResourceFileAsync", "NetworkGetEntityFromNetworkId",
    "NetworkGetEntityIsNetworked", "NetworkGetEntityOwner", "NetworkGetNetworkIdFromEntity",
    "PerformHttpRequest", "PerformHttpRequestAsync", "Player", "PlayerId", "PlayerPedId",
    "RegisterCommand", "RegisterNUICallback", "RegisterNetEvent", "RemoveCommand",
    "RemoveEventHandler", "RemoveVehicleWindow", "RequestModel", "RestartResource",
    "SaveResourceFile", "SendNuiMessage", "SetBlockingOfNonTemporaryEvents",
    "SetDriftTyresEnabled", "SetEntityCoords", "SetEntityHeading", "SetEntityInvincible",
    "SetHttpHandler", "SetHttpTimeout", "SetInterval", "SetModelAsNoLongerNeeded",
    "SetNuiFocus", "SetPlayerRoutingBucket", "SetResourceKvp", "SetResourceKvpMulti",
    "SetTextCentre", "SetTextColour", "SetTextEntry", "SetTextFont", "SetTextProportional",
    "SetTextScale", "SetTimeout", "SetVehicleBodyHealth", "SetVehicleColours",
    "SetVehicleCustomPrimaryColour", "SetVehicleCustomSecondaryColour",
    "SetVehicleDirtLevel", "SetVehicleDoorBroken", "SetVehicleEngineHealth",
    "SetVehicleExtra", "SetVehicleExtraColours", "SetVehicleFixed", "SetVehicleFuelLevel",
    "SetVehicleLivery", "SetVehicleMod", "SetVehicleModColor_1", "SetVehicleModColor_2",
    "SetVehicleModKit", "SetVehicleNeonLightEnabled", "SetVehicleNeonLightsColour",
    "SetVehicleNumberPlateText", "SetVehicleNumberPlateTextIndex", "SetVehicleOilLevel",
    "SetVehiclePetrolTankHealth", "SetVehicleRoofLivery", "SetVehicleTyreBurst",
    "SetVehicleTyreSmokeColor", "SetVehicleTyresCanBurst", "SetVehicleWheelType",
    "SetVehicleWindowTint", "StartExpensiveSynchronousShapeTestLosProbe", "StartResource",
    "StartScreenEffect", "StopResource", "StopScreenEffect", "TaskStartScenarioInPlace",
    "ToggleVehicleMod", "TriggerClientEvent", "TriggerEvent", "TriggerLatentClientEvent",
    "TriggerNuiCallback", "TriggerServerEvent", "Wait", "World3dToScreen2d", "citizen",
    "exports", "joaat", "json", "loads", "matrix3", "onClientResourceStart",
    "onClientResourceStop", "onResourceStart", "onResourceStop", "promise", "promise_new",
    "quaternion", "source", "vec2", "vec3", "vec4", "vector2", "vector3", "vector4",
}
-- END GENERATED read_globals

-- BEGIN GENERATED globals
-- GENERATED by tools/gen-luacheck.js. Do not edit by hand.
-- Regenerate with `npm run gen-luacheck`; CI runs it with --check.
--
-- What THIS repository defines and its own files hand to each other.
-- Each shared script loads into every consumer VM, so a module can only
-- reach its neighbour through a global. That is the design, not a leak,
-- and it is the reason these names are declared at all.
--
-- 64 names, read out of the source by build-libglobals.js.
globals = {
    "CIS_DUMP_TARGET", "Cis", "CisCache", "CisConfigUtil", "CisCurve", "CisDefaults",
    "CisDetect", "CisForgetPlayer", "CisGrid", "CisHeap", "CisHistogram", "CisId",
    "CisInterp", "CisInvokingAllowed", "CisJobCount", "CisJson", "CisLRU", "CisLibFailed",
    "CisLibReady", "CisLog", "CisNetOn", "CisOwned", "CisPending", "CisRandom", "CisRate",
    "CisRateBucketCount", "CisRateOk", "CisReadyState", "CisRegisterCallback",
    "CisRegistry", "CisRememberJob", "CisSecurityRebuild", "CisSecurityReport", "CisSemver",
    "CisSparse", "CisString", "CisSyncEnabled", "CisTable", "CisTime", "CisValidate",
    "CisWindow", "CisZonesContains", "CisZonesCreate", "CisZonesRemove", "Config",
    "CreatePed", "DebugLog", "DiscordConfig", "DrawText3D", "GetClosestVehicle",
    "GetCurrentWeaponData", "GetDistanceBetweenCoords", "GetPlayerVehicleSeat",
    "GetTableSize", "GetVehicleProperties", "GetWeaponAttachments", "Globals", "Logging",
    "RandomFloat", "RequestModelTimeout", "Round", "Security", "SetVehicleProperties",
    "WaitForLibReady",
}
-- END GENERATED globals

-- Everything below is a decision, not a default.

-- An unused LOCAL is the most useful thing this tool produces, and it is not
-- on by default. It stays on.
unused = true
unused_args = true

-- An argument named `_` is exempt, which is how a callback that has to match a
-- signature says so without silencing the rule for the whole file.
unused_secondaries = true

-- `self` in a method is a parameter, not a self-assignment.
self = false

-- W111 (setting an undefined global) and W113 (reading one) are on by default
-- and stay on. They are the rules that catch a misspelled native, which is a
-- runtime nil-index in a different subsystem entirely.
--
-- NOTE FOR THE NEXT EDITOR: the file previously set `undef`, `field`,
-- `mutating` and `shadowing` here, with comments explaining what each was for.
-- None of those is a luacheck 1.2.0 option. luacheck ignores keys it does not
-- recognise, so they did nothing at all and the comments described enforcement
-- that was not happening. Field access on a global table is deliberately not
-- reported: the library keeps its state in plain tables and reaches into them
-- by key.

-- Every file is linted. `exclude_files` used to hide client/cache.lua and
-- client/weapon.lua because they contain FiveM backtick hash literals, which
-- stock Lua cannot parse. tools/lint.js copies the tree to a temp folder and
-- replaces each backtick literal with a same-length placeholder, so those files
-- are checked like every other one and luacheck never sees the syntax it
-- cannot handle.

max_line_length = false
codes = true