---@meta

-- GENERATED by tools/gen-types.js from api.lua and the source. DO NOT EDIT.
--
-- `npm run gen-types` regenerates this; `npm run gen-types:check` fails
-- if the committed copy is stale. Editing it by hand produces a stub that
-- lies to every consumer who trusts it, which is worse than no stub.

--- The library
local cis_libs = {}

--- One class per realm, because several exports take DIFFERENT
--- arguments per realm -- DbQuery and GetDoorState are the examples.

-- ======================== client ========================
---@class cis_libs.AddDoorGroup
---@field use string no proxy equivalent; exports["cis_libs"]:AddDoorGroup(groupData)
---@field since string 1.0.0
---@field deprecated boolean false
---@param groupData any
function cis_libs.AddDoorGroup(groupData) end

---@deprecated
---@class cis_libs.AddDoorToSystem
---@field use string Cis.doors.add(doorData)
---@field since string 1.0.0
---@field deprecated boolean true
---@param newDoorData any
---@param internal any
function cis_libs.AddDoorToSystem(newDoorData, internal) end

---@class cis_libs.AutoLogError
---@field use string Cis.log.error(message) from inside a pcall
---@field since string 1.0.0
---@field deprecated boolean false
---@param err any
---@param event any
function cis_libs.AutoLogError(err, event) end

---@class cis_libs.AwaitCallback
---@field use string Cis.callback.await(name, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
function cis_libs.AwaitCallback(name) end

---@class cis_libs.CallCallback
---@field use string Cis.callback.call(name, cb, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param cb any
function cis_libs.CallCallback(name, cb) end

---@class cis_libs.CreatePed
---@field use string no proxy equivalent; returns 0 on an invalid or unloaded model
---@field since string 1.0.0
---@field deprecated boolean false
---@param model any
---@param coords any
---@param heading any
---@param options any
function cis_libs.CreatePed(model, coords, heading, options) end

---@class cis_libs.CreateTarget
---@field use string Cis.target.add(zoneType, name, coords, size, options)
---@field since string 1.0.0
---@field deprecated boolean false
---@param zoneType any
---@param name any
---@param coords any
---@param size any
---@param options any
function cis_libs.CreateTarget(zoneType, name, coords, size, options) end

---@class cis_libs.CreateZone
---@field use string Cis.zones.box / Cis.zones.poly / Cis.zones.sphere
---@field since string 1.0.0
---@field deprecated boolean false
---@param kind any
---@param name any
---@param a any
---@param b any
---@param options any
function cis_libs.CreateZone(kind, name, a, b, options) end

---@class cis_libs.DebugLog
---@field use string Cis.log.debug(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
function cis_libs.DebugLog(message) end

---@class cis_libs.DetectDatabase
---@field use string Asks the server which driver is running. Returns { name, resource, version, how, reason }
---@field since string 2.0.0
---@field deprecated boolean false
---@param configured any
function cis_libs.DetectDatabase(configured) end

---@class cis_libs.DetectFramework
---@field use string Asks the server what framework it is actually running. Returns { name, resource, version, how, reason }
---@field since string 2.0.0
---@field deprecated boolean false
---@param configured any
---@param custom any
function cis_libs.DetectFramework(configured, custom) end

---@class cis_libs.DrawText3D
---@field use string no proxy equivalent
---@field since string 1.0.0
---@field deprecated boolean false
---@param x any
---@param y any
---@param z any
---@param text any
---@param settings any
function cis_libs.DrawText3D(x, y, z, text, settings) end

---@class cis_libs.GetCachedHeading
---@field use string Cis.player.heading(), which reads the native directly in a consumer VM
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetCachedHeading() end

---@class cis_libs.GetCachedPed
---@field use string Cis.player.ped(), which reads the native directly in a consumer VM
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetCachedPed() end

---@class cis_libs.GetCachedServerId
---@field use string Cis.player.serverId()
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetCachedServerId() end

---@class cis_libs.GetCachedVehicle
---@field use string Cis.player.vehicle()
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetCachedVehicle() end

---@class cis_libs.GetCachedWeapon
---@field use string Cis.player.weapon()
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetCachedWeapon() end

---@class cis_libs.GetCapabilities
---@field use string The one call that answers "which of my four resources is actually running". Returns { [slot] = { owner, resolved } }
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.GetCapabilities() end

---@class cis_libs.GetClientConfig
---@field use string no proxy equivalent; the config the server sent to this client
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetClientConfig() end

---@class cis_libs.GetClientLogging
---@field use string Cis.log.debug / info / warn / error
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetClientLogging() end

---@class cis_libs.GetClosestDoor
---@field use string no proxy equivalent; exports["cis_libs"]:GetClosestDoor()
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetClosestDoor() end

---@class cis_libs.GetClosestVehicle
---@field use string no proxy equivalent; a 5 unit forward ray, then a 5 unit radius search
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetClosestVehicle() end

---@class cis_libs.GetCurrentWeaponData
---@field use string Cis.player.weapon()
---@field since string 1.0.0
---@field deprecated boolean false
---@param ped any
function cis_libs.GetCurrentWeaponData(ped) end

---@class cis_libs.GetDistanceBetweenCoords
---@field use string no proxy equivalent
---@field since string 1.0.0
---@field deprecated boolean false
---@param x1 any
---@param y1 any
---@param z1 any
---@param x2 any
---@param y2 any
---@param z2 any
function cis_libs.GetDistanceBetweenCoords(x1, y1, z1, x2, y2, z2) end

---@class cis_libs.GetDoorState
---@field use string Cis.doors.get(id)
---@field since string 1.0.0
---@field deprecated boolean false
---@param doorId any
function cis_libs.GetDoorState(doorId) end

---@deprecated
---@class cis_libs.GetFramework
---@field use string Cis.framework.player(src) on the server; Cis.framework.notify on the client. Not an API: it returns a table of callable references
---@field since string 1.0.0
---@field deprecated boolean true
function cis_libs.GetFramework() end

---@deprecated
---@class cis_libs.GetGlobals
---@field use string Cis.player.* and Cis.sync.*; there is no single replacement
---@field since string 1.0.0
---@field deprecated boolean true
function cis_libs.GetGlobals() end

---@class cis_libs.GetKnownTargets
---@field use string The ordered framework and driver tables detection uses. Shared so a product cannot disagree with the debug output about what is running
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.GetKnownTargets() end

---@class cis_libs.GetPlayerVehicleSeat
---@field use string Cis.player.vehicle(), second return value
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetPlayerVehicleSeat() end

---@deprecated
---@class cis_libs.GetPolyzones
---@field use string Cis.zones.poly / Cis.zones.remove / Cis.zones.contains
---@field since string 1.0.0
---@field deprecated boolean true
function cis_libs.GetPolyzones() end

---@class cis_libs.GetSyncedEntities
---@field use string no proxy equivalent; the id-to-handle table of everything this client spawned
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetSyncedEntities() end

---@class cis_libs.GetTableSize
---@field use string no proxy equivalent
---@field since string 1.0.0
---@field deprecated boolean false
---@param t any
function cis_libs.GetTableSize(t) end

---@class cis_libs.GetVehicleProperties
---@field use string no proxy equivalent; the full property snapshot used by sync
---@field since string 1.0.0
---@field deprecated boolean false
---@param vehicle any
function cis_libs.GetVehicleProperties(vehicle) end

---@class cis_libs.GetZoneDebug
---@field use string no proxy equivalent; the last grid pass cost in milliseconds
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetZoneDebug() end

---@class cis_libs.InventoryCount
---@field use string Cis.inventory.count(item) on the client, Cis.inventory.count(src, item) on the server
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
function cis_libs.InventoryCount(src, item) end

---@class cis_libs.InventoryHas
---@field use string Cis.inventory.has(...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
---@param amount any
function cis_libs.InventoryHas(src, item, amount) end

---@class cis_libs.IsReady
---@field use string Cis.isReady, or Cis.ready(cb)
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.IsReady() end

---@class cis_libs.LogDebug
---@field use string Cis.log.debug(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogDebug(message, discordType) end

---@class cis_libs.LogError
---@field use string Cis.log.error(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
---@param errorInfo any
function cis_libs.LogError(message, discordType, errorInfo) end

---@class cis_libs.LogInfo
---@field use string Cis.log.info(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogInfo(message, discordType) end

---@class cis_libs.LogWarn
---@field use string Cis.log.warn(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogWarn(message, discordType) end

---@class cis_libs.Notify
---@field use string Cis.framework.notify(...). The two-argument client form sends `kind` in the message slot; this is pinned as a known defect in test/contracts.lua and is a MAJOR change to correct
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param message any
---@param kind any
function cis_libs.Notify(src, message, kind) end

---@class cis_libs.OnPlayerCache
---@field use string Cis.player.on(key, cb). The cb cannot cross the boundary; use a net event
---@field since string 1.0.0
---@field deprecated boolean false
---@param key any
---@param cb any
function cis_libs.OnPlayerCache(key, cb) end

---@class cis_libs.RandomFloat
---@field use string no proxy equivalent
---@field since string 1.0.0
---@field deprecated boolean false
---@param lower any
---@param greater any
function cis_libs.RandomFloat(lower, greater) end

---@class cis_libs.RegisterCallback
---@field use string Cis.callback.register(name, handler)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param handler any
function cis_libs.RegisterCallback(name, handler) end

---@class cis_libs.RegisterCapability
---@field use string Called by cis_core, cis_bridge and cis_keys with (slot, "resource:Export"). First registration wins
---@field since string 2.0.0
---@field deprecated boolean false
---@param slot any
---@param provider any
function cis_libs.RegisterCapability(slot, provider) end

---@class cis_libs.RemoveTarget
---@field use string Cis.target.remove(name, isPed)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param isPed any
function cis_libs.RemoveTarget(name, isPed) end

---@class cis_libs.RemoveZone
---@field use string Cis.zones.remove(name)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
function cis_libs.RemoveZone(name) end

---@class cis_libs.RequestInventorySync
---@field use string Cis.inventory.count is a hint. This asks for a fresh one. Client only
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.RequestInventorySync() end

---@class cis_libs.RequestLockDoors
---@field use string Cis.doors.setState(id, true) on the client
---@field since string 1.0.0
---@field deprecated boolean false
---@param identifier any
function cis_libs.RequestLockDoors(identifier) end

---@class cis_libs.RequestModelTimeout
---@field use string Cis.streaming.model(model, timeout)
---@field since string 1.0.0
---@field deprecated boolean false
---@param model any
---@param timeout any
function cis_libs.RequestModelTimeout(model, timeout) end

---@class cis_libs.RequestUnlockDoors
---@field use string Cis.doors.setState(id, false) on the client
---@field since string 1.0.0
---@field deprecated boolean false
---@param identifier any
function cis_libs.RequestUnlockDoors(identifier) end

---@class cis_libs.Round
---@field use string no proxy equivalent; math round to n places
---@field since string 1.0.0
---@field deprecated boolean false
---@param num any
---@param numDecimalPlaces any
function cis_libs.Round(num, numDecimalPlaces) end

---@class cis_libs.SetVehicleProperties
---@field use string no proxy equivalent; diffs against the last applied snapshot
---@field since string 1.0.0
---@field deprecated boolean false
---@param vehicle any
---@param props any
---@param fixVehicle any
function cis_libs.SetVehicleProperties(vehicle, props, fixVehicle) end

---@class cis_libs.TargetAvailable
---@field use string no proxy equivalent; true when a configured target provider is started
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.TargetAvailable() end

---@class cis_libs.TargetExists
---@field use string Cis.target.exists(name)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
function cis_libs.TargetExists(name) end

---@class cis_libs.TriggerLibCallback
---@field use string the client-to-server round trip whose callback receives only the results
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param cb any
function cis_libs.TriggerLibCallback(name, cb) end

---@class cis_libs.TryAwaitCallback
---@field use string Cis.callback.tryAwait(name, ...) -> ok, ... on success; false, reason on a refusal
---@field since string 2.1.0
---@field deprecated boolean false
---@param name any
function cis_libs.TryAwaitCallback(name) end

---@class cis_libs.UpdateTarget
---@field use string Cis.target.update(name, options)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param newOptions any
function cis_libs.UpdateTarget(name, newOptions) end

---@class cis_libs.WaitReady
---@field use string Cis.ready(cb, timeout) or Cis.wait(timeout)
---@field since string 1.0.0
---@field deprecated boolean false
---@param timeout any
function cis_libs.WaitReady(timeout) end

---@class cis_libs.WatchNear
---@field use string Cis.player.near(coords, distance, onEnter, onExit, onEnterEvent, onExitEvent)
---@field since string 1.0.0
---@field deprecated boolean false
---@param coords any
---@param distance any
---@param onEnter any
---@param onExit any
---@param onEnterEvent any
---@param onExitEvent any
function cis_libs.WatchNear(coords, distance, onEnter, onExit, onEnterEvent, onExitEvent) end

---@class cis_libs.ZoneContains
---@field use string Cis.zones.contains(name, point)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param point any
function cis_libs.ZoneContains(name, point) end


-- ======================== server ========================
---@class cis_libs.AddDoorGroup
---@field use string no proxy equivalent; exports["cis_libs"]:AddDoorGroup(groupData)
---@field since string 1.0.0
---@field deprecated boolean false
---@param groupData any
function cis_libs.AddDoorGroup(groupData) end

---@deprecated
---@class cis_libs.AddDoorToSystem
---@field use string Cis.doors.add(doorData)
---@field since string 1.0.0
---@field deprecated boolean true
---@param newDoorData any
---@param internal any
function cis_libs.AddDoorToSystem(newDoorData, internal) end

---@class cis_libs.AutoLogError
---@field use string Cis.log.error(message) from inside a pcall
---@field since string 1.0.0
---@field deprecated boolean false
---@param err any
---@param event any
function cis_libs.AutoLogError(err, event) end

---@class cis_libs.AwaitCallback
---@field use string Cis.callback.await(name, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
function cis_libs.AwaitCallback(name) end

---@class cis_libs.AwaitCallbackClient
---@field use string Cis.callback.awaitClient(src, name, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param target any
function cis_libs.AwaitCallbackClient(name, target) end

---@class cis_libs.BreakDoor
---@field use string no proxy equivalent; exports["cis_libs"]:BreakDoor(identifier)
---@field since string 1.0.0
---@field deprecated boolean false
---@param identifier any
function cis_libs.BreakDoor(identifier) end

---@class cis_libs.CallCallback
---@field use string Cis.callback.call(name, cb, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param cb any
function cis_libs.CallCallback(name, cb) end

---@class cis_libs.CallCallbackClient
---@field use string Cis.callback.callClient(src, name, cb, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param target any
---@param cb any
function cis_libs.CallCallbackClient(name, target, cb) end

---@deprecated
---@class cis_libs.CheckResourceVersion
---@field use string Config.CheckVersion and Config.VersionCheckUrl
---@field since string 1.0.0
---@field deprecated boolean true
---@param resourceName any
---@param resourceUrl any
---@param currentVersion any
function cis_libs.CheckResourceVersion(resourceName, resourceUrl, currentVersion) end

---@deprecated
---@class cis_libs.CreateSafeCallback
---@field use string Cis.callback.register(name, handler); this skips the name and handler checks
---@field since string 1.0.0
---@field deprecated boolean true
---@param name any
---@param cb any
function cis_libs.CreateSafeCallback(name, cb) end

---@deprecated
---@class cis_libs.DatabaseDelete
---@field use string Cis.db.query(sql, params)
---@field since string 1.0.0
---@field deprecated boolean true
---@param sql any
---@param params any
---@param cb any
function cis_libs.DatabaseDelete(sql, params, cb) end

---@deprecated
---@class cis_libs.DatabaseExecute
---@field use string Cis.db.query(sql, params)
---@field since string 1.0.0
---@field deprecated boolean true
---@param query any
---@param params any
---@param cb any
function cis_libs.DatabaseExecute(query, params, cb) end

---@deprecated
---@class cis_libs.DatabaseFetchAll
---@field use string Cis.db.query(sql, params)
---@field since string 1.0.0
---@field deprecated boolean true
---@param query any
---@param params any
---@param cb any
function cis_libs.DatabaseFetchAll(query, params, cb) end

---@deprecated
---@class cis_libs.DatabaseFetchOne
---@field use string Cis.db.single(sql, params)
---@field since string 1.0.0
---@field deprecated boolean true
---@param query any
---@param params any
---@param cb any
function cis_libs.DatabaseFetchOne(query, params, cb) end

---@deprecated
---@class cis_libs.DatabaseInsert
---@field use string Cis.db.insert(sql, params)
---@field since string 1.0.0
---@field deprecated boolean true
---@param sql any
---@param params any
---@param cb any
function cis_libs.DatabaseInsert(sql, params, cb) end

---@deprecated
---@class cis_libs.DatabaseUpdate
---@field use string Cis.db.update(sql, params)
---@field since string 1.0.0
---@field deprecated boolean true
---@param sql any
---@param params any
---@param cb any
function cis_libs.DatabaseUpdate(sql, params, cb) end

---@class cis_libs.DbInsert
---@field use string Cis.db.insert(sql, params)
---@field since string 1.0.0
---@field deprecated boolean false
---@param sql any
---@param params any
function cis_libs.DbInsert(sql, params) end

---@class cis_libs.DbQuery
---@field use string Cis.db.query(sql, params)
---@field since string 1.0.0
---@field deprecated boolean false
---@param sql any
---@param params any
function cis_libs.DbQuery(sql, params) end

---@class cis_libs.DbScalar
---@field use string Cis.db.scalar(sql, params)
---@field since string 1.0.0
---@field deprecated boolean false
---@param sql any
---@param params any
function cis_libs.DbScalar(sql, params) end

---@class cis_libs.DbSingle
---@field use string Cis.db.single(sql, params)
---@field since string 1.0.0
---@field deprecated boolean false
---@param sql any
---@param params any
function cis_libs.DbSingle(sql, params) end

---@class cis_libs.DbTransaction
---@field use string Cis.db.transaction(queries). oxmysql only; queries are oxmysql array-of-{query, values} entries
---@field since string 1.0.0
---@field deprecated boolean false
---@param queries any
function cis_libs.DbTransaction(queries) end

---@class cis_libs.DbUpdate
---@field use string Cis.db.update(sql, params)
---@field since string 1.0.0
---@field deprecated boolean false
---@param sql any
---@param params any
function cis_libs.DbUpdate(sql, params) end

---@class cis_libs.DetectDatabase
---@field use string Asks the server which driver is running. Returns { name, resource, version, how, reason }
---@field since string 2.0.0
---@field deprecated boolean false
---@param configured any
function cis_libs.DetectDatabase(configured) end

---@class cis_libs.DetectFramework
---@field use string Asks the server what framework it is actually running. Returns { name, resource, version, how, reason }
---@field since string 2.0.0
---@field deprecated boolean false
---@param configured any
---@param custom any
function cis_libs.DetectFramework(configured, custom) end

---@class cis_libs.FixDoor
---@field use string no proxy equivalent; exports["cis_libs"]:FixDoor(identifier)
---@field since string 1.0.0
---@field deprecated boolean false
---@param identifier any
function cis_libs.FixDoor(identifier) end

---@class cis_libs.GetAllDoorData
---@field use string no proxy equivalent; the full door and group tables
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetAllDoorData() end

---@class cis_libs.GetCapabilities
---@field use string The one call that answers "which of my four resources is actually running". Returns { [slot] = { owner, resolved } }
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.GetCapabilities() end

---@class cis_libs.GetConfigSummary
---@field use string no proxy equivalent; the non-secret half of the server config
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetConfigSummary() end

---@class cis_libs.GetDiscordConfig
---@field use string The outbound/webhook configuration SetConfig was handed, for the capability that does the sending. Server realm only -- it holds webhook URLs and is deliberately not on the client payload whitelist
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.GetDiscordConfig() end

---@class cis_libs.GetDiscordQueueDepth
---@field use string no proxy equivalent; queued message count and dropped count
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetDiscordQueueDepth() end

---@class cis_libs.GetDoorState
---@field use string Cis.doors.get(id)
---@field since string 1.0.0
---@field deprecated boolean false
---@param doorId any
function cis_libs.GetDoorState(doorId) end

---@deprecated
---@class cis_libs.GetFramework
---@field use string Cis.framework.player(src) on the server; Cis.framework.notify on the client. Not an API: it returns a table of callable references
---@field since string 1.0.0
---@field deprecated boolean true
function cis_libs.GetFramework() end

---@class cis_libs.GetKnownTargets
---@field use string The ordered framework and driver tables detection uses. Shared so a product cannot disagree with the debug output about what is running
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.GetKnownTargets() end

---@class cis_libs.GetLibsPrefix
---@field use string no proxy equivalent; the configured Security.EventPrefix
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetLibsPrefix() end

---@class cis_libs.GetLogging
---@field use string Cis.log.debug / info / warn / error
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.GetLogging() end

---@class cis_libs.GetNormalizedPlayer
---@field use string Cis.framework.player(src)
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
function cis_libs.GetNormalizedPlayer(src) end

---@class cis_libs.GetOnlineJobCount
---@field use string no proxy equivalent; the callback cis_libs:getOnlineJobCount
---@field since string 1.0.0
---@field deprecated boolean false
---@param jobs any
function cis_libs.GetOnlineJobCount(jobs) end

---@class cis_libs.InventoryAdd
---@field use string Cis.inventory.add(src, item, amount, metadata)
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
---@param amount any
---@param metadata any
function cis_libs.InventoryAdd(src, item, amount, metadata) end

---@class cis_libs.InventoryCount
---@field use string Cis.inventory.count(item) on the client, Cis.inventory.count(src, item) on the server
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
function cis_libs.InventoryCount(src, item) end

---@class cis_libs.InventoryHas
---@field use string Cis.inventory.has(...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
---@param amount any
function cis_libs.InventoryHas(src, item, amount) end

---@class cis_libs.InventoryRemove
---@field use string Cis.inventory.remove(src, item, amount)
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
---@param amount any
function cis_libs.InventoryRemove(src, item, amount) end

---@class cis_libs.InvokingAllowed
---@field use string no proxy equivalent; ask before mutating. This is the supported way to avoid a refusal
---@field since string 1.0.0
---@field deprecated boolean false
function cis_libs.InvokingAllowed() end

---@deprecated
---@class cis_libs.LockDoors
---@field use string Cis.doors.setState(identifier, true)
---@field since string 1.0.0
---@field deprecated boolean true
---@param identifier any
function cis_libs.LockDoors(identifier) end

---@class cis_libs.LogDebug
---@field use string Cis.log.debug(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogDebug(message, discordType) end

---@class cis_libs.LogError
---@field use string Cis.log.error(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
---@param errorInfo any
function cis_libs.LogError(message, discordType, errorInfo) end

---@class cis_libs.LogInfo
---@field use string Cis.log.info(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogInfo(message, discordType) end

---@class cis_libs.LogWarn
---@field use string Cis.log.warn(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogWarn(message, discordType) end

---@class cis_libs.Notify
---@field use string Cis.framework.notify(...). The two-argument client form sends `kind` in the message slot; this is pinned as a known defect in test/contracts.lua and is a MAJOR change to correct
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param message any
---@param kind any
function cis_libs.Notify(src, message, kind) end

---@class cis_libs.NotifyClient
---@field use string Called by a product to show a notification to one client, without hardcoding the event name owned by this library
---@field since string 2.0.0
---@field deprecated boolean false
---@param src any
---@param message any
---@param kind any
function cis_libs.NotifyClient(src, message, kind) end

---@class cis_libs.PublishInventory
---@field use string Called by the inventory service. Pushes cis_libs:client:inventory to one player
---@field since string 2.0.0
---@field deprecated boolean false
---@param src any
function cis_libs.PublishInventory(src) end

---@class cis_libs.PublishJobUpdate
---@field use string Called by cis_core when a player changes job. Fires cis_libs:jobUpdated, so the event name stays owned by this library
---@field since string 2.0.0
---@field deprecated boolean false
---@param job any
---@param src any
function cis_libs.PublishJobUpdate(job, src) end

---@class cis_libs.PublishPlayerLoaded
---@field use string Called by cis_core when a player object exists. Fires cis_libs:playerLoaded
---@field since string 2.0.0
---@field deprecated boolean false
---@param job any
---@param src any
function cis_libs.PublishPlayerLoaded(job, src) end

---@class cis_libs.RateOk
---@field use string no proxy equivalent; a resource may share the library rate limiter
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param name any
---@param windowMs any
---@param maxHits any
function cis_libs.RateOk(src, name, windowMs, maxHits) end

---@class cis_libs.RegisterCallback
---@field use string Cis.callback.register(name, handler)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param handler any
function cis_libs.RegisterCallback(name, handler) end

---@class cis_libs.RegisterCapability
---@field use string Called by cis_core, cis_bridge and cis_keys with (slot, "resource:Export"). First registration wins
---@field since string 2.0.0
---@field deprecated boolean false
---@param slot any
---@param provider any
function cis_libs.RegisterCapability(slot, provider) end

---@class cis_libs.SecureNetOn
---@field use string Cis.net.on(name, fn, opts) -> true when the event was bound
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param fn any
---@param opts any
function cis_libs.SecureNetOn(name, fn, opts) end

---@class cis_libs.SecurityReport
---@field use string Cis.security.report(src, reason)
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param reason any
function cis_libs.SecurityReport(src, reason) end

---@class cis_libs.SendDiscordLog
---@field use string Cis.log.info with a discordType; no proxy equivalent for a raw webhook push
---@field since string 1.0.0
---@field deprecated boolean false
---@param webhookURL any
---@param title any
---@param message any
---@param color any
---@param ping any
function cis_libs.SendDiscordLog(webhookURL, title, message, color, ping) end

---@class cis_libs.SetConfig
---@field use string Called by cis_core at boot with (config, security, discord). First registration wins; a second is refused and named
---@field since string 2.0.0
---@field deprecated boolean false
---@param config any
---@param security any
---@param discord any
function cis_libs.SetConfig(config, security, discord) end

---@class cis_libs.SetDropPlayerHandler
---@field use string Called by whoever ships the config, with "resource:Export". A FUNCTION cannot be sent across the boundary, which is why this exists
---@field since string 2.0.0
---@field deprecated boolean false
---@param provider any
function cis_libs.SetDropPlayerHandler(provider) end

---@class cis_libs.SyncCreate
---@field use string Cis.sync.ped / Cis.sync.prop / Cis.sync.vehicle
---@field since string 1.0.0
---@field deprecated boolean false
---@param kind any
---@param data any
function cis_libs.SyncCreate(kind, data) end

---@class cis_libs.SyncRemove
---@field use string Cis.sync.remove(id)
---@field since string 1.0.0
---@field deprecated boolean false
---@param id any
function cis_libs.SyncRemove(id) end

---@class cis_libs.TryAwaitCallback
---@field use string Cis.callback.tryAwait(name, ...) -> ok, ... on success; false, reason on a refusal
---@field since string 2.1.0
---@field deprecated boolean false
---@param name any
function cis_libs.TryAwaitCallback(name) end

---@deprecated
---@class cis_libs.UnlockDoors
---@field use string Cis.doors.setState(identifier, false)
---@field since string 1.0.0
---@field deprecated boolean true
---@param identifier any
function cis_libs.UnlockDoors(identifier) end

---@class cis_libs.UnregisterCapability
---@field use string Called by a product on shutdown or handover. Only the slot owner may release it
---@field since string 2.0.0
---@field deprecated boolean false
---@param slot any
function cis_libs.UnregisterCapability(slot) end

---@class cis_libs.WaitCapability
---@field use string Waits up to timeoutMs for a capability slot to be filled. Returns true and the owner, or nil and a reason naming the slot. No proxy equivalent -- a consumer waits from its own resource.
---@field since string 2.1.0
---@field deprecated boolean false
---@param slot any
---@param timeoutMs any
function cis_libs.WaitCapability(slot, timeoutMs) end

---@class cis_libs.WaitReady
---@field use string Cis.ready(cb, timeout) or Cis.wait(timeout)
---@field since string 1.0.0
---@field deprecated boolean false
---@param timeout any
function cis_libs.WaitReady(timeout) end


-- ======================== both ========================
---@class cis_libs.AddDoorGroup
---@field use string no proxy equivalent; exports["cis_libs"]:AddDoorGroup(groupData)
---@field since string 1.0.0
---@field deprecated boolean false
---@param groupData any
function cis_libs.AddDoorGroup(groupData) end

---@deprecated
---@class cis_libs.AddDoorToSystem
---@field use string Cis.doors.add(doorData)
---@field since string 1.0.0
---@field deprecated boolean true
---@param newDoorData any
---@param internal any
function cis_libs.AddDoorToSystem(newDoorData, internal) end

---@class cis_libs.AutoLogError
---@field use string Cis.log.error(message) from inside a pcall
---@field since string 1.0.0
---@field deprecated boolean false
---@param err any
---@param event any
function cis_libs.AutoLogError(err, event) end

---@class cis_libs.AwaitCallback
---@field use string Cis.callback.await(name, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
function cis_libs.AwaitCallback(name) end

---@class cis_libs.CallCallback
---@field use string Cis.callback.call(name, cb, ...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param cb any
function cis_libs.CallCallback(name, cb) end

---@class cis_libs.DetectDatabase
---@field use string Asks the server which driver is running. Returns { name, resource, version, how, reason }
---@field since string 2.0.0
---@field deprecated boolean false
---@param configured any
function cis_libs.DetectDatabase(configured) end

---@class cis_libs.DetectFramework
---@field use string Asks the server what framework it is actually running. Returns { name, resource, version, how, reason }
---@field since string 2.0.0
---@field deprecated boolean false
---@param configured any
---@param custom any
function cis_libs.DetectFramework(configured, custom) end

---@class cis_libs.GetCapabilities
---@field use string The one call that answers "which of my four resources is actually running". Returns { [slot] = { owner, resolved } }
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.GetCapabilities() end

---@class cis_libs.GetDoorState
---@field use string Cis.doors.get(id)
---@field since string 1.0.0
---@field deprecated boolean false
---@param doorId any
function cis_libs.GetDoorState(doorId) end

---@deprecated
---@class cis_libs.GetFramework
---@field use string Cis.framework.player(src) on the server; Cis.framework.notify on the client. Not an API: it returns a table of callable references
---@field since string 1.0.0
---@field deprecated boolean true
function cis_libs.GetFramework() end

---@class cis_libs.GetKnownTargets
---@field use string The ordered framework and driver tables detection uses. Shared so a product cannot disagree with the debug output about what is running
---@field since string 2.0.0
---@field deprecated boolean false
function cis_libs.GetKnownTargets() end

---@class cis_libs.InventoryCount
---@field use string Cis.inventory.count(item) on the client, Cis.inventory.count(src, item) on the server
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
function cis_libs.InventoryCount(src, item) end

---@class cis_libs.InventoryHas
---@field use string Cis.inventory.has(...)
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param item any
---@param amount any
function cis_libs.InventoryHas(src, item, amount) end

---@class cis_libs.LogDebug
---@field use string Cis.log.debug(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogDebug(message, discordType) end

---@class cis_libs.LogError
---@field use string Cis.log.error(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
---@param errorInfo any
function cis_libs.LogError(message, discordType, errorInfo) end

---@class cis_libs.LogInfo
---@field use string Cis.log.info(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogInfo(message, discordType) end

---@class cis_libs.LogWarn
---@field use string Cis.log.warn(message)
---@field since string 1.0.0
---@field deprecated boolean false
---@param message any
---@param discordType any
function cis_libs.LogWarn(message, discordType) end

---@class cis_libs.Notify
---@field use string Cis.framework.notify(...). The two-argument client form sends `kind` in the message slot; this is pinned as a known defect in test/contracts.lua and is a MAJOR change to correct
---@field since string 1.0.0
---@field deprecated boolean false
---@param src any
---@param message any
---@param kind any
function cis_libs.Notify(src, message, kind) end

---@class cis_libs.RegisterCallback
---@field use string Cis.callback.register(name, handler)
---@field since string 1.0.0
---@field deprecated boolean false
---@param name any
---@param handler any
function cis_libs.RegisterCallback(name, handler) end

---@class cis_libs.RegisterCapability
---@field use string Called by cis_core, cis_bridge and cis_keys with (slot, "resource:Export"). First registration wins
---@field since string 2.0.0
---@field deprecated boolean false
---@param slot any
---@param provider any
function cis_libs.RegisterCapability(slot, provider) end

---@class cis_libs.TryAwaitCallback
---@field use string Cis.callback.tryAwait(name, ...) -> ok, ... on success; false, reason on a refusal
---@field since string 2.1.0
---@field deprecated boolean false
---@param name any
function cis_libs.TryAwaitCallback(name) end

---@class cis_libs.WaitReady
---@field use string Cis.ready(cb, timeout) or Cis.wait(timeout)
---@field since string 1.0.0
---@field deprecated boolean false
---@param timeout any
function cis_libs.WaitReady(timeout) end

--- Every raw export name again, flattened, for a consumer that wants
--- one lookup rather than two realm-specific classes.
cis_libs.AddDoorGroup = cis_libs.AddDoorGroup
cis_libs.AddDoorToSystem = cis_libs.AddDoorToSystem
cis_libs.AutoLogError = cis_libs.AutoLogError
cis_libs.AwaitCallback = cis_libs.AwaitCallback
cis_libs.AwaitCallbackClient = cis_libs.AwaitCallbackClient
cis_libs.BreakDoor = cis_libs.BreakDoor
cis_libs.CallCallback = cis_libs.CallCallback
cis_libs.CallCallbackClient = cis_libs.CallCallbackClient
cis_libs.CheckResourceVersion = cis_libs.CheckResourceVersion
cis_libs.CreatePed = cis_libs.CreatePed
cis_libs.CreateSafeCallback = cis_libs.CreateSafeCallback
cis_libs.CreateTarget = cis_libs.CreateTarget
cis_libs.CreateZone = cis_libs.CreateZone
cis_libs.DatabaseDelete = cis_libs.DatabaseDelete
cis_libs.DatabaseExecute = cis_libs.DatabaseExecute
cis_libs.DatabaseFetchAll = cis_libs.DatabaseFetchAll
cis_libs.DatabaseFetchOne = cis_libs.DatabaseFetchOne
cis_libs.DatabaseInsert = cis_libs.DatabaseInsert
cis_libs.DatabaseUpdate = cis_libs.DatabaseUpdate
cis_libs.DbInsert = cis_libs.DbInsert
cis_libs.DbQuery = cis_libs.DbQuery
cis_libs.DbScalar = cis_libs.DbScalar
cis_libs.DbSingle = cis_libs.DbSingle
cis_libs.DbTransaction = cis_libs.DbTransaction
cis_libs.DbUpdate = cis_libs.DbUpdate
cis_libs.DebugLog = cis_libs.DebugLog
cis_libs.DetectDatabase = cis_libs.DetectDatabase
cis_libs.DetectFramework = cis_libs.DetectFramework
cis_libs.DrawText3D = cis_libs.DrawText3D
cis_libs.FixDoor = cis_libs.FixDoor
cis_libs.GetAllDoorData = cis_libs.GetAllDoorData
cis_libs.GetCachedHeading = cis_libs.GetCachedHeading
cis_libs.GetCachedPed = cis_libs.GetCachedPed
cis_libs.GetCachedServerId = cis_libs.GetCachedServerId
cis_libs.GetCachedVehicle = cis_libs.GetCachedVehicle
cis_libs.GetCachedWeapon = cis_libs.GetCachedWeapon
cis_libs.GetCapabilities = cis_libs.GetCapabilities
cis_libs.GetClientConfig = cis_libs.GetClientConfig
cis_libs.GetClientLogging = cis_libs.GetClientLogging
cis_libs.GetClosestDoor = cis_libs.GetClosestDoor
cis_libs.GetClosestVehicle = cis_libs.GetClosestVehicle
cis_libs.GetConfigSummary = cis_libs.GetConfigSummary
cis_libs.GetCurrentWeaponData = cis_libs.GetCurrentWeaponData
cis_libs.GetDiscordConfig = cis_libs.GetDiscordConfig
cis_libs.GetDiscordQueueDepth = cis_libs.GetDiscordQueueDepth
cis_libs.GetDistanceBetweenCoords = cis_libs.GetDistanceBetweenCoords
cis_libs.GetDoorState = cis_libs.GetDoorState
cis_libs.GetFramework = cis_libs.GetFramework
cis_libs.GetGlobals = cis_libs.GetGlobals
cis_libs.GetKnownTargets = cis_libs.GetKnownTargets
cis_libs.GetLibsPrefix = cis_libs.GetLibsPrefix
cis_libs.GetLogging = cis_libs.GetLogging
cis_libs.GetNormalizedPlayer = cis_libs.GetNormalizedPlayer
cis_libs.GetOnlineJobCount = cis_libs.GetOnlineJobCount
cis_libs.GetPlayerVehicleSeat = cis_libs.GetPlayerVehicleSeat
cis_libs.GetPolyzones = cis_libs.GetPolyzones
cis_libs.GetSyncedEntities = cis_libs.GetSyncedEntities
cis_libs.GetTableSize = cis_libs.GetTableSize
cis_libs.GetVehicleProperties = cis_libs.GetVehicleProperties
cis_libs.GetZoneDebug = cis_libs.GetZoneDebug
cis_libs.InventoryAdd = cis_libs.InventoryAdd
cis_libs.InventoryCount = cis_libs.InventoryCount
cis_libs.InventoryHas = cis_libs.InventoryHas
cis_libs.InventoryRemove = cis_libs.InventoryRemove
cis_libs.InvokingAllowed = cis_libs.InvokingAllowed
cis_libs.IsReady = cis_libs.IsReady
cis_libs.LockDoors = cis_libs.LockDoors
cis_libs.LogDebug = cis_libs.LogDebug
cis_libs.LogError = cis_libs.LogError
cis_libs.LogInfo = cis_libs.LogInfo
cis_libs.LogWarn = cis_libs.LogWarn
cis_libs.Notify = cis_libs.Notify
cis_libs.NotifyClient = cis_libs.NotifyClient
cis_libs.OnPlayerCache = cis_libs.OnPlayerCache
cis_libs.PublishInventory = cis_libs.PublishInventory
cis_libs.PublishJobUpdate = cis_libs.PublishJobUpdate
cis_libs.PublishPlayerLoaded = cis_libs.PublishPlayerLoaded
cis_libs.RandomFloat = cis_libs.RandomFloat
cis_libs.RateOk = cis_libs.RateOk
cis_libs.RegisterCallback = cis_libs.RegisterCallback
cis_libs.RegisterCapability = cis_libs.RegisterCapability
cis_libs.RemoveTarget = cis_libs.RemoveTarget
cis_libs.RemoveZone = cis_libs.RemoveZone
cis_libs.RequestInventorySync = cis_libs.RequestInventorySync
cis_libs.RequestLockDoors = cis_libs.RequestLockDoors
cis_libs.RequestModelTimeout = cis_libs.RequestModelTimeout
cis_libs.RequestUnlockDoors = cis_libs.RequestUnlockDoors
cis_libs.Round = cis_libs.Round
cis_libs.SecureNetOn = cis_libs.SecureNetOn
cis_libs.SecurityReport = cis_libs.SecurityReport
cis_libs.SendDiscordLog = cis_libs.SendDiscordLog
cis_libs.SetConfig = cis_libs.SetConfig
cis_libs.SetDropPlayerHandler = cis_libs.SetDropPlayerHandler
cis_libs.SetVehicleProperties = cis_libs.SetVehicleProperties
cis_libs.SyncCreate = cis_libs.SyncCreate
cis_libs.SyncRemove = cis_libs.SyncRemove
cis_libs.TargetAvailable = cis_libs.TargetAvailable
cis_libs.TargetExists = cis_libs.TargetExists
cis_libs.TriggerLibCallback = cis_libs.TriggerLibCallback
cis_libs.TryAwaitCallback = cis_libs.TryAwaitCallback
cis_libs.UnlockDoors = cis_libs.UnlockDoors
cis_libs.UnregisterCapability = cis_libs.UnregisterCapability
cis_libs.UpdateTarget = cis_libs.UpdateTarget
cis_libs.WaitCapability = cis_libs.WaitCapability
cis_libs.WaitReady = cis_libs.WaitReady
cis_libs.WatchNear = cis_libs.WatchNear
cis_libs.ZoneContains = cis_libs.ZoneContains

return cis_libs
