// T6 + T7. One tool, two outputs, from one source of truth.
//
//   types/cis_libs.lua        a ---@meta stub describing every export
//   DOCUMENTATION.md §5 and §6, between the generated markers
//
// BOTH ARE COMMITTED AND CI FAILS IF EITHER IS STALE. That is the whole point.
// A generated file refreshed on demand is documentation nobody reads, because
// the reader has no way to tell it from the file it drifted away from.
//
// WHY THE DUMPER IS A SEPARATE LUA FILE. The first attempt walked api.lua's
// table off the fengari C-API stack from JavaScript and got the stack discipline
// wrong several frames from the mistake -- "table expected", with no reference
// to the table being walked. Every level of that recursion is an index into a
// stack whose shape depends on the values above it. Lua can dump itself with no
// C API at all, so tools/lua-dump.lua does that, and JSON.parse handles the
// result on this side, where a malformed document is an ordinary error message.
const fs = require('fs')
const path = require('path')
const fengari = require('fengari')
const lua = fengari.lua
const lauxlib = fengari.lauxlib
const lualib = fengari.lualib
const toLua = fengari.to_luastring
const { scanResource } = require('./lua-exports')

const root = path.join(__dirname, '..')
const read = p => fs.readFileSync(path.join(root, p), 'utf8')

const OUT_TYPES = 'types/cis_libs.lua'
const OUT_DOC = 'DOCUMENTATION.md'
const BEGIN = '<!-- generated:begin -->'
const END = '<!-- generated:end -->'

function loadApi() {
  const L = lauxlib.luaL_newstate()
  lualib.luaL_openlibs(L)
  lua.lua_pushstring(L, toLua('api.lua'))
  lua.lua_setglobal(L, toLua('CIS_DUMP_TARGET'))
  const src = read('tools/lua-dump.lua')
  // Loaded and called with ONE result asked for, because the dumper RETURNS the
  // document rather than printing it: fengari's node stdout does not pass
  // through process.stdout.write, so capturing output catches nothing. A value
  // on the stack is unambiguous.
  if (lauxlib.luaL_loadstring(L, toLua(src)) !== lua.LUA_OK ||
      lua.lua_pcall(L, 0, 1, 0) !== lua.LUA_OK) {
    throw new Error('lua-dump.lua: ' + lua.lua_tojsstring(L, -1))
  }
  return JSON.parse(lua.lua_tojsstring(L, -1))
}

function sigFor(d, realm) {
  const s = d.signature
  if (s && typeof s === 'object') return s[realm] || s.client || s.server || '()'
  return s || '()'
}

// Argument NAMES, filtered to things that are valid Lua parameter names.
//
// api.lua writes '(name, ...)' for a variadic signature, and 'any ...' is not
// a parameter list -- the generated stub has to PARSE, not merely look right.
// The syntax checker caught that one, which is the argument for running a
// syntax check over generated output at all: the file looked correct and did
// not load. A signature that reduces to nothing yields no parameters, which is
// the honest rendering of an argument list we cannot read.
function argNames(sig) {
  // Sliced, not regexed. The earlier version used a regex and the shell ate
  // its backslashes twice on the way in, which is a silly way to lose an hour.
  const text = String(sig)
  const open = text.indexOf(String.fromCharCode(40))
  const close = text.lastIndexOf(String.fromCharCode(41))
  if (open < 0 || close < open) return []
  return text.slice(open + 1, close).split(',')
    .map(x => x.trim())
    .filter(x => /^[A-Za-z_][A-Za-z0-9_]*$/.test(x))
}

function oneLine(s) {
  return String(s || '').replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim()
}

// ---------------------------------------------------------------------------
function buildTypes(api, surface) {
  const L = []
  L.push('---@meta')
  L.push('')
  L.push('-- GENERATED by tools/gen-types.js from api.lua and the source. DO NOT EDIT.')
  L.push('--')
  L.push('-- `npm run gen-types` regenerates this; `npm run gen-types:check` fails')
  L.push('-- if the committed copy is stale. Editing it by hand produces a stub that')
  L.push('-- lies to every consumer who trusts it, which is worse than no stub.')
  L.push('')
  L.push('--- The library')
  L.push('local cis_libs = {}')
  L.push('')

  const exports = api.exports || {}
  const names = Object.keys(exports).sort()
  L.push('--- One class per realm, because several exports take DIFFERENT')
  L.push('--- arguments per realm -- DbQuery and GetDoorState are the examples.')
  for (const realm of ['client', 'server', 'both']) {
    L.push('')
    L.push(`-- ======================== ${realm} ========================`)
    for (const name of names) {
      const d = exports[name] || {}
      const dRealm = d.realm || 'both'
      if (dRealm !== realm && dRealm !== 'both') continue
      if (realm === 'both' && dRealm !== 'both') continue
      if (d.deprecated) L.push('---@deprecated')
      const sig = sigFor(d, dRealm === 'both' ? 'server' : dRealm)
      const args = argNames(sig)
      L.push(`---@class cis_libs.${name}`)
      L.push(`---@field use string ${oneLine(d.use)}`)
      L.push(`---@field since string ${d.since || ''}`)
      L.push(`---@field deprecated boolean ${d.deprecated ? 'true' : 'false'}`)
      // The TYPE goes in a ---@param line ABOVE, and the declaration carries
      // bare names. 'function f(any x)' is not Lua -- it parses as an expression
      // and dies on the first parameter. The syntax checker found that.
      for (const a of args) L.push(`---@param ${a} any`)
      L.push(`function cis_libs.${name}(${args.join(', ')}) end`)
      L.push('')
    }
  }

  L.push('--- Every raw export name again, flattened, for a consumer that wants')
  L.push('--- one lookup rather than two realm-specific classes.')
  for (const name of names) {
    L.push(`cis_libs.${name} = cis_libs.${name}`)
  }
  L.push('')
  L.push('return cis_libs')
  return L.join('\n') + '\n'
}

// ---------------------------------------------------------------------------
function buildDocTables(api) {
  const L = []
  const exports = api.exports || {}
  L.push('| Export | Realm | Signature | Since | Notes |')
  L.push('|---|---|---|---|---|')
  for (const name of Object.keys(exports).sort()) {
    const d = exports[name] || {}
    const realm = d.realm || 'both'
    const sig = realm === 'both' ? sigFor(d, 'server') : sigFor(d, realm)
    const notes = [
      oneLine(d.use),
      d.deprecated ? '**deprecated**' : '',
      d.stable === false ? 'unstable' : '',
    ].filter(Boolean).join(' ')
    L.push(`| \`${name}\` | ${realm} | \`${sig.replace(/\|/g, '\\|')}\` | ${d.since || '—'} | ${notes} |`)
  }
  L.push('')
  if (api.events) {
    L.push('| Event | Since | Payload |')
    L.push('|---|---|---|')
    for (const name of Object.keys(api.events).sort()) {
      const e = api.events[name] || {}
      L.push(`| \`${name}\` | ${e.since || '—'} | ${oneLine(e.payload)} |`)
    }
    L.push('')
  }
  return L.join('\n')
}

// ---------------------------------------------------------------------------
// Refuses to guess where to write. A generated block with no marker is a
// hand-maintained block that LOOKS generated, which is the worst of both.
function replaceBetween(text, generated, label) {
  const begin = text.indexOf(BEGIN)
  const endIdx = text.indexOf(END)
  if (begin < 0 || endIdx < 0 || endIdx < begin) {
    throw new Error(`${label} has no ${BEGIN} / ${END} markers`)
  }
  return text.slice(0, begin + BEGIN.length) + '\n\n' + generated + '\n\n' + text.slice(endIdx)
}

// Compare and write in one line ending, always LF.
//
// Git may hand this file CRLF (core.autocrlf on a Windows checkout) while the
// generated string is LF. A raw byte compare then reports a phantom difference
// on a tree where nothing changed -- which trains everyone to ignore the
// staleness check, and an ignored staleness check catches no drift at all.
const nl = s => s.replace(/\r\n/g, '\n')

function main() {
  const check = process.argv.includes('--check')
  const api = loadApi()
  const surface = scanResource(root)
  let stale = false

  const types = buildTypes(api, surface)
  const typesPath = path.join(root, OUT_TYPES)
  const existing = fs.existsSync(typesPath) ? nl(fs.readFileSync(typesPath, 'utf8')) : null
  if (existing !== nl(types)) {
    if (check) { console.error(`FAIL ${OUT_TYPES} is stale. Run: npm run gen-types`); stale = true } else {
      fs.mkdirSync(path.dirname(typesPath), { recursive: true })
      fs.writeFileSync(typesPath, nl(types))
      console.log(`wrote ${OUT_TYPES}`)
    }
  } else {
    console.log(`${OUT_TYPES} up to date`)
  }

  const docPath = path.join(root, OUT_DOC)
  const doc = nl(fs.readFileSync(docPath, 'utf8'))
  let nextDoc
  try {
    nextDoc = replaceBetween(doc, buildDocTables(api), OUT_DOC)
  } catch (e) {
    console.error(String(e.message))
    process.exitCode = 1
    return
  }
  if (nextDoc !== doc) {
    if (check) { console.error(`FAIL ${OUT_DOC} is stale. Run: npm run gen-types`); stale = true } else {
      fs.writeFileSync(docPath, nl(nextDoc))
      console.log(`wrote ${OUT_DOC}`)
    }
  } else {
    console.log(`${OUT_DOC} up to date`)
  }

  if (stale) process.exitCode = 1
}

main()