// Stage 1.1: run the real luacheck over every shipped file, including the two
// that use FiveM backtick hash literals.
//
// WHY A WRAPPER. `` `WEAPON_UNARMED` `` is valid CfxLua and a syntax error to
// every stock Lua parser, stock luacheck included. The old answer was
// exclude_files, which meant client/cache.lua and client/weapon.lua were never
// linted at all -- two of the files most likely to hold an unused local and a
// misspelled native, since they are the ones nobody can run luacheck on.
//
// THE ANSWER. Copy the tree to a temp folder, replace every backtick literal
// with a placeholder of EXACTLY the same length, and lint that. Same length
// means every line number and column number luacheck reports still points at
// the right place in the real file, so the output is reported against the
// original paths and is directly clickable. The source is never modified.
//
// The placeholder is a valid Lua expression of equal length so the parse
// succeeds for the right reason: `WEAPON_UNARMED` (20 chars) becomes a
// quoted string of the same length.

const fs = require('fs')
const os = require('os')
const path = require('path')
const { spawnSync } = require('child_process')

const root = path.join(__dirname, '..')

// Places luacheck may be. An explicit env var wins so CI can pin its own.
function findLuacheck() {
  if (process.env.LUACHECK) return process.env.LUACHECK
  const exe = process.platform === 'win32' ? 'luacheck.exe' : 'luacheck'
  const candidates = [
    path.join(os.homedir(), '.cis-devtools', exe),
    path.join(root, 'node_modules', '.bin', exe),
    path.join(root, 'node_modules', '.bin', 'luacheck'),
  ]
  for (const c of candidates) {
    try { fs.accessSync(c, fs.constants.X_OK); return c } catch { /* keep looking */ }
  }
  return exe // fall back to PATH and let the error be legible
}

// Files luacheck must not be pointed at, each with the reason printed on every
// run so the exclusion can never become silent.
//
// The plan's objection to the old `exclude_files` was that two SOURCE files
// were hidden for a reason that tooling could have solved. That is fixed: the
// backtick problem is handled above, and client/cache.lua and client/weapon.lua
// are linted like everything else. These two are a different category.
//
//   fxmanifest.lua   is a FiveM manifest DSL, not Lua. `game 'gta5'` and
//                   `client_scripts { ... }` are declarations; run through a
//                   Lua parser every directive is an undefined global, and
//                   "fx_version is not defined" is a fact about the DSL, not a
//                   defect. Its correctness is checked by test/contracts.lua
//                   and by tools/validate-api.js, which read it as a manifest.
//   types/*.lua      is GENERATED by tools/gen-types.js. It is a LuaLS
//                   annotation stub: `function cis_libs.TryAwaitCallback(name)`
//                   has an empty body on purpose, so every parameter is unused
//                   and every declaration writes a global. Two hundred and
//                   forty-seven findings, none of which says anything about the
//                   code. Its correctness is checked by `npm run gen-types:check`.
const EXCLUDED = [
  { match: /^fxmanifest\.lua$/, why: 'FiveM manifest DSL, not Lua' },
  { match: /^types\//, why: 'generated LuaLS annotation stub (npm run gen-types:check covers it)' },
]

// Every Lua file the manifest loads, plus the test and tool trees that are not
// shipped but are still ours to lint.
function collectTargets() {
  const out = []
  const walk = (dir, rel) => {
    let ents
    try { ents = fs.readdirSync(dir, { withFileTypes: true }) } catch { return }
    for (const e of ents) {
      if (e.name === 'node_modules' || e.name === '.git' || e.name === 'dist') continue
      const full = path.join(dir, e.name)
      const r = rel ? rel + '/' + e.name : e.name
      if (e.isDirectory()) walk(full, r)
      else if (e.isFile() && e.name.endsWith('.lua')) out.push(r)
    }
  }
  walk(root, '')
  return out.filter(rel => !EXCLUDED.some(x => x.match.test(rel))).sort()
}

// Replace every backtick-delimited run with a same-length run of DIGITS.
//
// Digits, specifically. An earlier version emitted a run of 'x', which is an
// IDENTIFIER, and luacheck correctly reported every one of them as an
// undefined global -- twenty-four W113s in client/weapon.lua that were an
// artefact of the wrapper rather than anything about the code. A same-length
// run of digits is a numeric literal: valid Lua, correct arity, no name, no
// warning, and every byte after it keeps its original offset.
//
// STRING-AWARE, and it has to be. test/client.lua contains the line
//     local BACKTICK_PATTERN = '`([^`]*)`'
// whose backticks are inside a string literal. Blanking only one of a pair
// gives '1([^1]*)1' and turns the whole line into an unfinished string, which is
// how luacheck first reported
//     test/client.lua:366:26: (E011) unfinished string
// A hash literal is only a hash literal when it is not inside a string.
const DIGITS = '1234567890'
function neutraliseBackticks(src) {
  let out = ''
  let i = 0
  const n = src.length
  while (i < n) {
    const c = src[i]
    if (c === '"' || c === "'") {
      const quote = c
      let j = i + 1
      while (j < n) {
        if (src[j] === '\\') { j += 2; continue }
        if (src[j] === quote || src[j] === '\n') break
        j++
      }
      out += src.slice(i, j + 1)
      i = j + 1
      continue
    }
    if (c === '-' && src[i + 1] === '-') {
      // Comments are copied through untouched: a backtick in a comment is
      // documentation, not a hash literal, and leaving it alone keeps the
      // comment readable in any diagnostic.
      const end = src.indexOf('\n', i)
      const stop = end === -1 ? n : end
      out += src.slice(i, stop)
      i = stop
      continue
    }
    if (c === '`') {
      const end = src.indexOf('`', i + 1)
      if (end > i) {
        for (let k = i; k <= end; k++) out += DIGITS[(k - i) % DIGITS.length]
        i = end + 1
        continue
      }
    }
    out += c
    i++
  }
  return out
}

function main() {
  const luacheck = findLuacheck()
  const targets = collectTargets()
  if (!targets.length) {
    console.error('no Lua files found')
    process.exit(2)
  }

  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'cis-luacheck-'))
  let patched = 0
  try {
    for (const rel of targets) {
      const src = fs.readFileSync(path.join(root, rel), 'utf8')
      const clean = neutraliseBackticks(src)
      const dest = path.join(tmp, rel)
      fs.mkdirSync(path.dirname(dest), { recursive: true })
      fs.writeFileSync(dest, clean, 'utf8')
      if (clean !== src) patched++
    }
    fs.copyFileSync(path.join(root, '.luacheckrc'), path.join(tmp, '.luacheckrc'))
    const testRc = path.join(root, 'test', '.luacheckrc')
    if (fs.existsSync(testRc)) fs.copyFileSync(testRc, path.join(tmp, 'test', '.luacheckrc'))

    console.log('lint: ' + targets.length + ' files' + (patched ? ' (' + patched + ' with backtick hash literals neutralised)' : ''))
    for (const x of EXCLUDED) console.log('  not linted: ' + x.match.source + ' -- ' + x.why)

    // luacheck resolves ONE config for the whole run; it does not pick up a
    // per-directory .luacheckrc as it descends. So the tree is linted twice,
    // once with each config, and the exit codes are combined.
    //
    // The split is the test tree and nothing else, because the test tree is the
    // only place that IMPLEMENTS the natives instead of calling them.
    const testFiles = targets.filter(t => t.startsWith('test/'))
    const otherFiles = targets.filter(t => !t.startsWith('test/'))

    const groups = []
    if (otherFiles.length) groups.push({ label: 'source', files: otherFiles, config: null })
    if (testFiles.length) groups.push({ label: 'test', files: testFiles, config: 'test/.luacheckrc' })

    let worst = 0
    let firstError = null
    for (const g of groups) {
      const args = [...g.files, '--codes']
      if (g.config) args.push('--config', g.config)
      const res = spawnSync(luacheck, args, {
        cwd: tmp,
        encoding: 'utf8',
        maxBuffer: 32 * 1024 * 1024,
        shell: process.platform === 'win32',
      })
      if (res.error && !firstError) firstError = res.error

      const out = (res.stdout || '') + (res.stderr || '')
      // Report the ORIGINAL paths, not the temp ones.
      const cleaned = out
        .split(tmp + path.sep).join('')
        .split(tmp.replace(/\\/g, '/') + '/').join('')
        .split(new RegExp(tmp.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g')).join('.')
      process.stdout.write(cleaned)

      const code = res.status === null ? 2 : res.status
      if (code > worst) worst = code
    }

    if (firstError) {
      console.error('could not run luacheck: ' + firstError.message)
      console.error('looked for: ' + luacheck)
      process.exit(2)
    }
    process.exit(worst)
  } finally {
    fs.rmSync(tmp, { recursive: true, force: true })
  }
}

main()